dist_thresh: 0.03
datasets:
- human
- mouse
references:
- silva
- rdp
- gg
weights:
- simple
methods:
- closed
ref_fracs:
    start: 5
    stop: 6
    step: 1
seeds: 100
configpath: 'config/config.yaml'
